# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ebullient·works
description: > # this means to ignore newlines until "baseurl:"
  Nothing poetic here, just a collection of things. Some are "how I did this so I can remember later", others are "this is totally cool!", and some are something else entirely.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ebullientworks.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: ""

author:
  - name: erin
  - github: https://github.com/ebullient
  - twitter: ebullientworks
  - uri: http://www.ebullientworks.com/

collections:
   pages:
     output: true
     permalink: /:path/

permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - README.md
  - import.rb
