title: ebullient·works
description: > # this means to ignore newlines until the next tag
  Nothing poetic here, just a collection of things. Some are "how I did this so I can remember later", others are "this is totally cool!", and some are something else entirely.
uglyURLs: true
disablePathToLower: true
disableLiveReload: true
publishDir: "../public"
languageCode: en-us
enableGitInfo: true
summaryLength: 1000
frontmatter:
  date:
    - ":filename"
    - ":git"
    - ":default"
  publishDate:
    - ":filename"
    - ":default"
outputs:
  home:
    - HTML
    - RSS
    - JSON
permalinks:
  posts: /:year/:month/:day/:slug
taxonomies:
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: false
    style: github
    tabWidth: 2
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
module:
  mounts:
  - source: ../projects/ttrpg-convert-cli/docs
    target: content/projects/ttrpg-convert-cli/docs
  - source: ../projects/ttrpg-convert-cli
    includeFiles: '*.md'
    target: content/projects/ttrpg-convert-cli
  - source: ../projects/
    includeFiles: '*.md'
    target: content/projects/
  - source: content
    target: content