title: ebullient·works
uglyURLs: true
disablePathToLower: true
disableLiveReload: true
publishDir: "../public"
enableGitInfo: true
summaryLength: 1000
params:
  description: > # this means to ignore newlines until the next tag
    Nothing poetic here, just a collection of things. Some are "how I did this so I can remember later", others are "this is totally cool!", and some are something else entirely.
frontmatter:
  date:
    - ":filename"
    - ":git"
    - ":default"
  publishDate:
    - ":filename"
    - ":default"
outputs:
  home:
    - HTML
    - RSS
    - JSON
permalinks:
  page:
    posts: /:year/:month/:day/:slug
  section:
    projects: /projects/

taxonomies:
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: false
    style: github
    tabWidth: 2
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
module:
  mounts:
  - source: ../overlays/
    target: content/projects/
  - source: ../projects/
    target: content/projects/
    includeFiles: "**/*.md"
  - source: content
    target: content