name: Check Links

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - uses: actions/checkout@v4

      - name: Check for broken links
        run: deno task checklinks